### ISSUE TITLE
Bold doesn't turn bold on Linux

### ISSUE THREAD

**Issue by Redsandro** [drudru/ansi_up#29] opened 2016-02-25 12:29 UTC
When using bold ansi like in chalk:
https://github.com/chalk/ansi-styles/blob/master/index.js#L31

I get bold on the terminal, but nothing on ansi_up.

**Comment by drudru** [comment] 2016-03-03 01:20
Hi - if you could send me a sample of the data, I will test it. Also, I'm about to release a new version. So I will be doing my testing on the new version. Thanks.

**Comment by Redsandro** [comment] 2016-03-03 10:11
It's hard to copy-paste the escape characters, so it's easier to just try. Make a new node like this (after `npm install chalk`):

```
var chalk = require('chalk');
console.log('This is some', chalk.bold('bold'), 'text.');
```

> This is some [1;37mbold[m text.

Basically, in Unix, every color can also be bold.

See: https://www.npmjs.com/package/chalk

![More examples](https://github.com/chalk/ansi-styles/raw/master/screenshot.png)
![](https://github.com/chalk/ansi-styles/raw/master/screenshot.png)

**Comment by Qix-** [comment] 2016-03-16 08:02
If this is happening on Linux, it's most likely happening everywhere.

**Comment by Redsandro** [comment] 2016-03-16 11:12
Not sure if I've ever seen bold on the Windows console. The default pixel map font does not have bold characters. I think what on Unix would be bold green, on Windows would be bright green. Not sure if this is still the same, my Windows console knowledge might lack a few versions behind.

**Comment by Qix-** [comment] 2016-03-16 14:42
You're correct. "Bold" on windows translates to bright colors.

**Comment by kjyv** [comment] 2016-11-08 17:53
It's most probably not related to linux at all but part of the ANSI code convention. The sequence ESC[1 is used for Bold or Bright following https://en.wikipedia.org/wiki/ANSI_escape_code (under Select Graphic Rendition parameters). The state can be reset with ESC[0 e.g. after a bold line.

**Comment by Qix-** [comment] 2016-11-08 20:40
> The state can be reset with ESC[0 e.g. after a bold line.

or `\e[21m`.

**Comment by hlieberman** [comment] 2017-02-05 17:25
Confirmed; the problem is not supporting ESC[1.

**Comment by hlieberman** [comment] 2017-02-06 04:07
So, I've narrowed it down to a bug in ansi_up.js:238.  The code checks only if the fg and bg are null, but doesn't handle the case where something is set to bright but still using the standard palette.

PR incoming, with test.

**Comment by hlieberman** [comment] 2017-02-06 04:17
Hm.  Looks like that's incomplete.  That's /an/ error, but it's not the only one.  Fixing that gets a span wrapping it, but it is blank.  The real problem is that bright is assumed to always be followed by another `num` containing more information.  I can't think of a particularly good way to fix this.

Easy reproduction:
```javascript
var x = "\033[1mBold White\033[0m";
ansi_up.ansi_to_html(x);
"<span style="">Bold White</span>"
```

**Comment by drudru** [comment] 2017-02-06 22:37
Hi guys - please try the TypeScript branch. I am going to finally do whatever is necessary to land that and make it master/push a new npm.

**Comment by hlieberman** [comment] 2017-02-07 01:42
This bug still affects the typescript branch.

```javascript
var x = new AnsiUp;
undefined
x.ansi_to_html("\033[1mFoo\033[0m");
"Foo"
```

**Comment by drudru** [comment] 2017-02-08 02:21
Ugh. confirmed. I will have this fixed tomorrow. Thanks for checking the TypeScript branch.

**Comment by drudru** [comment] 2017-02-09 00:25
Hi - I have fixed it in the TypeScript branch. Give it a go.

**Comment by hlieberman** [comment] 2017-02-10 23:32
Confirmed; the bug is fixed in the typescript branch.

Unrelatedly, it takes some manual effort to make typescript output compatible with current invocations; the typescript stuff all requires a loader be used, whereas currently it's just dumped into window.ansi_up.
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by drudru** [comment] 2017-02-11 06:36
Thanks.

Yes, I noticed that too. I am focusing on getting that old functionality back. I think TypeScript changed their module handling a while back. I'm also making the npm compatible with TypeScript so users can still use the js version, but TS users also get the types.

Thanks again for your attention on this.

**Comment by drudru** [comment] 2017-02-18 02:29
Fixed: https://github.com/drudru/ansi_up/commit/a26c17e71379773d61ebe50f66707eca8ce2971b

Not published to master or npm yet. I will close when that happens.

**Comment by drudru** [comment] 2017-06-21 21:26
Ok - npm pushed

**Closed by drudru** 2017-06-21 21:26 UTC
