### ISSUE TITLE
Does it store state between calls?

### ISSUE THREAD

**Issue by amatiasq** [drudru/ansi_up#6] opened 2014-09-15 22:47 UTC
Hi, I've a question I don't find the answer at the docs or the code.

If I call `ansi_up.ansi_to_html()` and the content ends with red fg color, the next time I call it the result will start with red? because I'm receiving the terminal output via stream and the stream may be paused anywhere. If the answer is no is there a class I could instantiate to store the state?

Also I don't find anything about underline, stroke, inverse or italics, is this supported?

**Comment by amatiasq** [comment] 2014-09-16 23:25
No idea, how can I know?
You can connect yourself but it's in spanish: mud.balzhur.org:5400

---

A. Matías Quezada
Senior Javascript Developer


2014-09-16 23:54 GMT+02:00  notifications@github.com:

**Comment by drudru** [comment] 2015-01-22 23:37
BTW, I left this open because I've started thinking about the state saving problem.

**Comment by gerred** [comment] 2015-02-24 03:17
It'd be nice if the API were a stream for this. ansi_stream could be the function.

**Comment by drudru** [comment] 2015-05-12 20:06
@gerred  - ugh - sorry - just saw this. What is your use case? I think I definitely need to consider this.

**Comment by drudru** [comment] 2015-05-16 01:37
ok - i'm dropping the ball on this. sorry. And then this weekend is Maker Faire too :-)
I will think about this in the coming week, for sure.

**Comment by gbmhunter** [comment] 2015-08-27 11:06
+1 for the ability to stream text @drudru! You would have to store state, as well as not release escape characters to the output until the full escape sequence had been validated or invalidated.

I am looking to use this for a terminal streaming application too.

**Comment by ketan** [comment] 2015-08-28 04:09
As long as you hold the instance of `ansi_up` across multiple calls. You can use it to parse streaming output.

I just created this jsfiddle to demonstrate http://jsfiddle.net/ketanpkr/kvwzz1pq/.

I think this issue should be marked closed.

**Comment by gbmhunter** [comment] 2015-08-29 08:19
Nice example. I'm just wanting to confirm that it will still work even if the escape sequence itself is split across multiple calls?

**Comment by ketan** [comment] 2015-08-29 08:21
I don't think that'd work, because of how strings are split and tokenised. This is not really a "streaming" parser of sorts.

**Comment by gbmhunter** [comment] 2015-08-29 08:29
Say this data is coming through a UART, and your serial port onReceive() handler gets passed an arbitrarily long amount of data. You want to parse this and display it to the user. The end of the data from one call might be the start of an escape sequence, while the start of the next event would contain the rest of it. Is this a definition of streaming?

I would think that the expected behaviour would be that on detection of the escape character, the parser would hold back from releasing any characters until the escape sequence was completely validated, or non-validated thru illegal syntax. Then the parser would release the data to the output. All the parser would have to do is maintain a small "hold buffer" of say up to 10 characters or so.

**Comment by drudru** [comment] 2015-09-13 00:45
@ketan - thanks for your words

@gbmhunter - requests like yours have been coming up over and over. In fact, there has been a significant push in the CS community for parsers that are non-blocking. I will start working on this today and post updates here. The next version will have this capability.

Also, I think you are correct about the low difficulty in maintaining the input buffer, so this is not as difficult as say some much more complex and nested CFG.

**Comment by gbmhunter** [comment] 2015-09-13 05:52
@drudru, awesome news, I look forward to the next release! Keep up the good work, I am very appreciative.

**Comment by drudru** [comment] 2015-10-19 22:24
Hi - here is the wip on this:

https://github.com/drudru/ansi_up/tree/typescript

It doesn't have to hold on to any text, either. It always returns a span given the current state.

**Comment by drudru** [comment] 2016-03-03 02:01
I will be moving to the typescript version either today or tomorrow. Nobody has to use typescript to use the new code, that is just what I was using to generate the js.
I will make it a point to indicate the new stateless feature in the Readme.

**Comment by drudru** [comment] 2019-02-11 23:00
OK - long time since last check-in on this.

I've re-written core parts of the library again. It is now well defined from a stateful perspective.
It will also buffer incomplete sequences if the library cannot render them.
Both of these are now noted in the docs.

**Closed by drudru** 2019-02-11 23:00 UTC

**Comment by gbmhunter** [comment] 2019-02-12 01:03
Thanks @drudru , great work!
